# This workflow synchronizes groups of labels that correspond
# to items of selection list in Trac. It controls that in each
# such case there is just one label of the list present.
# Furthermore in the case of the state it checks the labels
# to coincide with the corresponding review state.

name: Synchronize selection list lables

on:
  pull_request_review:
    types: [submitted]
  issues:
    types: [opened, reopened, closed, labeled, unlabeled]
  pull_request:
    types: [opened, reopened, closed, labeled, unlabeled]

jobs:
  synchronize:
    runs-on: ubuntu-latest
    steps:
      # Download the Python script
      - name: Download script
        id: download
        run: |
          curl -L -O "https://raw.githubusercontent.com/"$REPO"/master/.github/sync_labels.py"
          chmod a+x sync_labels.py
        env:
          REPO: ${{ github.repository }}

      # Perform synchronization
      - name: Call script
        run: ./sync_labels.py $ACTION $ISSUE_URL $PR_URL "$LABEL" "$REV_STATE"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ACTION: ${{ github.event.action }}
          ISSUE_URL: ${{ github.event.issue.html_url }}
          PR_URL: ${{ github.event.pull_request.html_url }}
          LABEL: ${{ github.event.label.name }}
          REV_STATE: ${{ github.event.review.state }}
